[project]
name = "django-heroicons"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django-cotton>=1.2.1",
    "django>=5.1.2",
]

[tool.uv]
dev-dependencies = [
    "beautifulsoup4>=4.12.3",
    "jinja2>=3.1.4",
    "requests>=2.32.3",
]
